module.exports.comentarios = [
    //Comentarios apropiados
"Ocupás un lugar especial en el corazón de cada uno de los integrantes de la Comunidad \"Cristo Rey\". Fortalecenos desde el cielo", 
"Su vocación de servicio siempre ha sido un ejemplo para todos los que recorrimos los patios del colegio. Su devoción a la virgen un recuerdo imborrable... que la casa de las hermanitas no sean espacios vacios de personas y llenos de recuerdos... Ojalá la congregación vuelva a darle vida a esos lugares que vieron recorrer a la hermana Carmen, Antonia, Brígida, Clementina y Ángela cuando yo era una niña.", 
"Los mejores recuerdos de mi niñez y juventud perdurarán siempre al lado de ella, con su sonrisa y sus manos cálidas sosteniéndonos para ingresar a la capilla... Gracias Hermana Carmen y hasta siempre...", 
"Dios te Bendiga Hermana Carmen", 
"Gracias a todos x acompañar a nuestro querido colegio C Rey!! Vamos x mas !!!", 
"MUY FELIZZ DIA MI QUERIDA AMIGA MUY CIERTAS TUS PALABRAS MARISA",
"FELIZ DIA SILVIA!!! ELLA SIEMPRE AGUANTANDONOS",
"Recen por las que muchos años estuvimos en ese preciado colegio", 
"Graciasss",
 "Bendiciones para toda la institución y el personal", 
"Muy hermoso el cuento", 
"Hermosa creación!!!! Gracias seño!!!!", 
"Hermosísimo",
"Gracias seño Cristina por el cariño y la paciencia!!!!!", 
"Valioso trabajo! Felicitaciones!", 
"Gracias Seño Cristina, por las demostraciones de cariño que ayuda al avance de los niños", 
"Que hermosa experiencia !!! Me emociona! !", 
"Valiosa experiencia!! Cómo late el corazón!! Abrazo a todos!!", 
"Hermoso año compartido! Gracias a todas las seños del Jardin Cristo Rey por tanta dedicacion y cariño! Valen amo su jardín!", 
"Hermoso año", 
"Hermoso momento compartimos ..nos divertimos mucho", 
"Felicitaciones a los alumnos de sala de 5 años, familias y docentes por tan valiosa obra y muy linda la celebración eucarística...", 
"Hermoso encuentro!!! Gracias a las Familias!!!", 
"que hermosa experiencia", 
"Hermoso momento de juegos con sus hijos. Felicitaciones", 
"Genial !!!!!!", 
"Como nos divertimos!!", 
"Espectacular me encanta", 
"Que gran verdad", 
"Realmente una genia!! Felicitaciones Lorena Vigna!!", 
"Hermosa experiencia! Felicitaciones para todos!!!", 
"Amén", 
"Hermoso verlos a los chicos participar del Festival en el Patio menor del Cabildo! Felicitaciones!", 
"Felicitaciones para todos! Hermosa experiencia !", 
"muy bueno!!!!!felicitaciones !!!!!!!!", 
"Que orgullo", 
"Orgullo de esos niños y jóvenes", 
"Que fantastico felicitaciones y orgullosa de ser ex alumna", 
"Muy cierto", 
"Excelente! Felicitaciones!", 
"Felicitaciones, Hermoso Acto de fin de curso!!", 
"FELICITACIONES!!! Un fuerte abrazo a cada una", 
"Felicitaciones queridas compañeras!!", 
"felicitaciones Rosana y Silvana por tantos años de abnegado servicio docente!!!", 
"Absolutamente cierto!", 
"Feliz proyecto!!!! Todas las actividades han sido para disfrutar de nuestros hijos y del jardin ! Gracias seños!!!!", 
"Hermoso proyecto! Pudimos disfrutar de cada etapa, participando o viendo a nuestros niños disfrutar las actividades! Gracias a las seños y todo el jardín", 
"Gracias a todos los docentes por permitirnos participar, compartir y disfrutar con nuestros hijos...Excelente idea la de trabajar juntos, familia y escuela...Felicitaciones!!!", 
"Gracias a Uds por hacernos parte de este hermoso proyecto!!! Felices de poder compartir con nuestros hijos esos momentos!!Felicitaciones!!!", 
"Gracias a Uds! Hermoso proyecto...Felices de poder participar y compartirlo con nuestros peques! Felicitaciones!!!", 
"Gracias a ustedes!Fue hermoso disfrutar de este exclente proyecto compartiendo con nuestros niños!", 
"Hermosa experiencia!!!Muchas gracias por permitirnos compartirla con nuestros niños! !", 
"Gracias por permitirnos compartir con nuestros hijos un momento tan lindo y especial en su infancia!!!", 
"Hermosa experiencia! Que lindo trabajaron! Felicitaciones por la iniciativa!!", 
"Que creatividad estos pequeños!!!! Gracias seño por permitirnos conocer este espacio!!", 
"Qué felices con la carpa!!", 
"Que buen proyecto", 
"La pasamos Barbaro!...muchas gracias!", 
"Hermoso momento de haber compartido con nuestros hijos juegos al aire libre!!!gracias seño Raquel a la institución", 
"Que felicidad !!! Excelente iniciativa por parte de las docentes!! Felicitaciones y gracias por permitirnos compartir con nuestros niños.", 
"Felices mis pequeños", 
"Que alegria tenian hermoso todo!!!", 
"Hermosos", 
"Muy entusiasmado mi peque... le encantó el taller", 
"Hermosa jornada!", 
"La pasamos genial",
"Hablar de mis primeros pasos en la educacion es hablar de la hermana Carmen ....",
"FELZZ DIAA QUERIDAS SEÑOS",
"Felicidades en su día",
"FELIZ FIESTA DE SANTO DOMINGO",
"Muchas graaaaaaaaaaaaacias",
"Hermosos",
"Feliz día para todas las seños!!!",
"Feliz día maestras jardineras!!!",
"Feliz dia chicas!!! besotes",
"Feliz día seños!!!!Dios las bendiga",
"Feliz día seños!!! Gracias por todo!",
"Qué hermoso momento compartido",
"Excelente la enseñanza",
"Es muy bueno",
"Es un colegio divino",
"Muy responsables y buena educación",
"Buena enseñanza",
"Excelente evento",
"Espectacular me encanta",
"Hermoso verlos a los chicos participar",
"Que lindo trabajaron",
"Excelente iniciativa por parte de las docentes",
"Felicidades a ese equipo maravilloso",
"Mi querido colegio",
"Hermosos recuerdos",
"Que lindo encuentro",
"Muy bello",
"Un hermoso día",
"El acto estuvo muy lindo",
"Lindos recuerdos",
"Espectacular",
"Precioso trabajo",
"Dedicación, prestigio y excelencia",
"La mejor educación de la ciudad",
"Gran grupo",
"Colegio muy familiar",
"Magnificas profesoras",
"Educación de calidad",
"Aplausos de pie para toda la institución",
"Felizzz Cumple querido Colegio Cristo Rey!!!!! Qué Dios los bendiga...",
"Felicidades querido Colegio. ..Que Dios proteja siempre a toda su comunidad",
"Muy Feliz cumpleaños Mí Cristo Rey hermoso!!!",
"Gracias por la información",
"Muy feliz cumple Hna. Carmen!!!",
"Ojalá se retome la ley del mayor esfuerzo!",
"Muy FeLiz cumple querida Hermana Carmen!!!! Un abrazo grande! Bendiciones",
"Hermoso ambiente para desarrollar conocimientos!",
"Querida Hna. Carmen que además también fuiste un poco mi mamá por varios años, SIEMPRE TENDRÁS TU LUGARCITO en mi corazón feliz cumpleaños y que EL SEÑOR TE COLME DE BENDICIONES",
"Estoy feliz de ver la pasión que ponen para enseñar y el trato excelente que tienen con los chicos, mi hijo está cada día más contento!",
"Muy feliz Navidad. Que Jesús siga bendiciendo nuestras familias y nuestra Comunidad Educativa",
"Felicidades para toda la Comunidad Educativa!!!",
"Felicidades a toda la comunidad del instituto Cristo Rey",
"FELICITACIONES !!!! PARA TODOS. SE NOTA EL TRABAJO Y DEDICACION Q LE PONEN. VAMOS POR MAS !!!!",
"Felicitaciones !!! tanto esfuerzo, alumnos y profesores, genios!!!!!!",
"Hermoso todo felicitaciones",
"Felicitaciones chicos!!!!! Gran día de ajedrez!!!",
"Felicitaciones!!!! Que lindo un domingo a puro ajedrez…",
"Felicitaciones a los jóvenes que participaron y a los organizadores.",
"Gracias al Museo por abrir sus puertas para que cada año podamos aprender más y valorar nuestra propia historia como pueblo y la inmensa riqueza natural de nuestra región. Impecable todo lo que se puede observar y excelente la disposición de Viviana Molli para atendernos con tanto agrado y amplios conocimientos para transmitirles a los chicos. Los niños trabajaron MUY BIEN!!!!!¡FELICITACIONES CHICOS!",
"FELIZZZZ DIAAA PARA TODOSSS",
"Felicidades a ese equipo maravilloso! Un beso largo",
"Feliz Dia a todos los niños...les desea la Comunidad de Cristo Rey",
"Felicidades a toda la comunidad de la que formo parte",
"La mejor elección para compartir la formación de mi hija",
"El orgullo de haber ido a ese colegio",
"Soy ex-alumna de este colegio; y es un hermoso espacio público para crecer",
"Muy cuidado y el uso de uniformes le da un toque único",
"El compañerismo es muy notable, los profesores muy buena onda",
"Inigualable. Si tuviera que elegir, nuevamente iría a este colegio",
"Mi mejores momentos de niñez y adolescencia en ese colegio que tanto amo",
"Edificaciones magnificas",

//Comentarios inapropiados
"Los profesores malisimos",
"El colegio es una porqueria",
"Es un colegio carteludo ",
"Es un colegio muy malo",
"Les importa solo la plata a los directores",
"Tuve una mala experiencia, no recomiendo el colegio",
"Pésimo profesores",
"Proyecto muy feo",
"En el acto la pasamos muy mal",
"Los profesores y directores tienen poca dedicación",
"Tuve muy malos recuerdos en el colegio",
"Desagradable el trabajo de las profesoras",
"La enseñanza es mala",
"Horrible establecimiento",
"Es un auténtico desastre el establecimiento",
"Los profesores no tienen motivación para enseñar ",
"Profesores sin preparación, y sin dedicación",
"Aplican una metodología pobre",
"Una vergüenza para la ciudad",
"El peor instituto que conocí",
"Hay poca disciplina en el colegio",
"Es un colegio elitista ",
"La forma de enseñar es malisima",
"Cero pedagogía de los profesores",
"Los actos son malos",
"Hace semanas que quiero coordinar una reunión con la profesora y no me da bola",
"Los profesores son estúpidos",
"El colegio se cae a pedazos",
"El colegio está sucio como la directora",
"El acto fue horrible, los chicos se dormían",
"El colegio es una porquería, los baños no tienen agua y están todas las instalaciones echa pedazos",
"Quiero el número de esa nena",
"La directora está siempre rascándose el culo",
"Tengo un recuerdo horrible de ese colegio",
"Las profesoras están constantemente maltratando",
"Me cansan las reuniones de padres, estoy podrida",
"La profesora Marta es muy prepotente y trata a todos los alumnos mal",
"Esa directora tiene olor, para mi no se baña",
"A todos en ese colegio le importa solo el dinero",
"A mi nene le dan todo el dia medicamentos sin autorización, me lo están drogando",
"Esa profesora no sirve para nada",
"Odio a esas profesoras",
"Mi hijo está cansado de ir al colegio porque las profesoras son insoportables",
"Mi hijo no puede ni verlas a las profesoras",
"Las profesoras son unas maleducadas",
"Las directoras maltratan a los estudiantes y les ponen sanciones cuando no van",
"La cuota es muy cara",
"El cacho está actuando de manera inapropiada con mi hijo",
"El portero está acosando a mi hijo",
"Cada vez que entro a ese colegio me da ganas de vomitar",
"La directora es la peor de todas, es una pelotuda",
"La vicedirectora le vive gritando a los chicos, de verdad, ¿no tiene otra forma de comunicarse?",
"La hermana carmen es super infeliz por estar rodeada de tanta gente como ustedes",
"Siempre promulgando la ley del menor esfuerzo",
"A los chicos tienen que enseñarle valores, dejense de joder con la historia y geografía ",
"La directora parece que fuma porro",
"Nadie hace nada, que se sepa la verdad sobre éste colegio de mierda",
"Los chicos viven perdiendo el tiempo y a mi me duele el bolsillo ",
"Al colegio le importa más su imagen que sus alumnos",
"Los chicos salen de ahí sin saber nada, no los quieren agarrar para ningún trabajo ",
"A la educación sexual la están dando muy mal y no están ayudando a los chicos, que es la idea",
"El gimnasio donde practican esta echo pedazos",
"En el gimnasio se ven cucarachas y alacranes por todos lados, a mi no me gusta que mis hijos vayan ahi  ",
"Las profesoras no saben usar la tecnología y los chicos se aburren",
"La metodología de enseñanza no es adecuada para las generaciones actuales, los chicos se aburren y no aprenden nada",
"Enseñan a que los chicos aprendan a estudiar de memoria, y a los dos días no se acuerdan una mierda",
"Los profesores son muy chismosos y critican a los estudiantes",
"Las profesoras no tienen ganas de dar clases y solo piensan en el sueldo",
"Las docentes viven de paro no trabajan nunca",
"Al final estoy pagando una cuota y la educación es una mierda",
"Los profesores hacen diferencia entre los nenes adinerados y los que no",
"En el cristo rey solamente se aprueba por cara",
"La docente tiene olor a cigarrillo cuando entra a dar clase, es una vergüenza !",
"Mi hijo se hizo pis encima porque la profesora no lo dejó ir al baño",
"Los docentes no se siguen capacitando por eso todo lo que enseñan es viejo ",
"Los tratan tan mal a los chicos que parece que están en un régimen militar",
"Colegio demasiado ortodoxo para estas épocas",
"Lugar donde se forrean desde los compañeritos de primaria hasta las mismas autoridades y docentes entre sí mismos",
"Es un colegio vergonzoso, la información es confusa, los padres no pueden opinar ni participar, solo pagar",
"Muy decepcionada con el colegio",
"Una basura el colegio no tratan en bullying",
"Muy pocos valores se respetan a la hora de dar una clase o con los directivos.",
"No actúan contra el maltrato",
"Son muy ratas, no venden ni fruta en el kiosco y eso que es una ley vender comida saludable",
"Aumentan la cuota y no nos dan ningún beneficio, no recomiendo el colegio",
"Muy autoritario en cuanto a la forma de vestir",
"Demasiado comunista, como si a Dios le importara cómo van vestidos, y mas en esta época de crisis, super exigentes y nada tolerantes",
]
