module.exports.comentarios_inapropiados = [
"Los profesores malisimos",
"El colegio es una porqueria",
"Es un colegio carteludo ",
"Es un colegio muy malo",
"Les importa solo la plata a los directores",
"Tuve una mala experiencia, no recomiendo el colegio",
"Pésimo profesores",
"Proyecto muy feo",
"En el acto la pasamos muy mal",
"Los profesores y directores tienen poca dedicación",
"Tuve muy malos recuerdos en el colegio",
"Desagradable el trabajo de las profesoras",
"La enseñanza es mala",
"Horrible establecimiento",
"Es un auténtico desastre el establecimiento",
"Los profesores no tienen motivación para enseñar ",
"Profesores sin preparación, y sin dedicación",
"Aplican una metodología pobre",
"Una vergüenza para la ciudad",
"El peor instituto que conocí",
"Hay poca disciplina en el colegio",
"Es un colegio elitista ",
"La forma de enseñar es malisima",
"Cero pedagogía de los profesores",
"Los actos son malos",
"Hace semanas que quiero coordinar una reunión con la profesora y no me da bola",
"Los profesores son estúpidos",
"El colegio se cae a pedazos",
"El colegio está sucio como la directora",
"El acto fue horrible, los chicos se dormían",
"El colegio es una porquería, los baños no tienen agua y están todas las instalaciones echa pedazos",
"Quiero el número de esa nena",
"La directora está siempre rascándose el culo",
"Tengo un recuerdo horrible de ese colegio",
"Las profesoras están constantemente maltratando",
"Me cansan las reuniones de padres, estoy podrida",
"La profesora Marta es muy prepotente y trata a todos los alumnos mal",
"Esa directora tiene olor, para mi no se baña",
"A todos en ese colegio le importa solo el dinero",
"A mi nene le dan todo el dia medicamentos sin autorización, me lo están drogando",
"Esa profesora no sirve para nada",
"Odio a esas profesoras",
"Mi hijo está cansado de ir al colegio porque las profesoras son insoportables",
"Mi hijo no puede ni verlas a las profesoras",
"Las profesoras son unas maleducadas",
"Las directoras maltratan a los estudiantes y les ponen sanciones cuando no van",
"La cuota es muy cara",
"El cacho está actuando de manera inapropiada con mi hijo",
"El portero está acosando a mi hijo",
"Cada vez que entro a ese colegio me da ganas de vomitar",
"La directora es la peor de todas, es una pelotuda",
"La vicedirectora le vive gritando a los chicos, de verdad, ¿no tiene otra forma de comunicarse?",
"La hermana carmen es super infeliz por estar rodeada de tanta gente como ustedes",
"Siempre promulgando la ley del menor esfuerzo",
"A los chicos tienen que enseñarle valores, dejense de joder con la historia y geografía ",
"La directora parece que fuma porro",
"Nadie hace nada, que se sepa la verdad sobre éste colegio de mierda",
"Los chicos viven perdiendo el tiempo y a mi me duele el bolsillo ",
"Al colegio le importa más su imagen que sus alumnos",
"Los chicos salen de ahí sin saber nada, no los quieren agarrar para ningún trabajo ",
"A la educación sexual la están dando muy mal y no están ayudando a los chicos, que es la idea",
"El gimnasio donde practican esta echo pedazos",
"En el gimnasio se ven cucarachas y alacranes por todos lados, a mi no me gusta que mis hijos vayan ahi  ",
"Las profesoras no saben usar la tecnología y los chicos se aburren",
"La metodología de enseñanza no es adecuada para las generaciones actuales, los chicos se aburren y no aprenden nada",
"Enseñan a que los chicos aprendan a estudiar de memoria, y a los dos días no se acuerdan una mierda",
"Los profesores son muy chismosos y critican a los estudiantes",
"Las profesoras no tienen ganas de dar clases y solo piensan en el sueldo",
"Las docentes viven de paro no trabajan nunca",
"Al final estoy pagando una cuota y la educación es una mierda",
"Los profesores hacen diferencia entre los nenes adinerados y los que no",
"En el cristo rey solamente se aprueba por cara",
"La docente tiene olor a cigarrillo cuando entra a dar clase, es una vergüenza !",
"Mi hijo se hizo pis encima porque la profesora no lo dejó ir al baño",
"Los docentes no se siguen capacitando por eso todo lo que enseñan es viejo ",
"Los tratan tan mal a los chicos que parece que están en un régimen militar",
"Colegio demasiado ortodoxo para estas épocas",
"Lugar donde se forrean desde los compañeritos de primaria hasta las mismas autoridades y docentes entre sí mismos",
"Es un colegio vergonzoso, la información es confusa, los padres no pueden opinar ni participar, solo pagar",
"Muy decepcionada con el colegio",
"Una basura el colegio no tratan en bullying",
"Muy pocos valores se respetan a la hora de dar una clase o con los directivos.",
"No actúan contra el maltrato",
"Son muy ratas, no venden ni fruta en el kiosco y eso que es una ley vender comida saludable",
"Aumentan la cuota y no nos dan ningún beneficio, no recomiendo el colegio",
"Muy autoritario en cuanto a la forma de vestir",
"Demasiado comunista, como si a Dios le importara cómo van vestidos, y mas en esta época de crisis, super exigentes y nada tolerantes",
]
